#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Mar 22, 2016 03:37:13 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.scr47
    set site_3_0 $base.scr48
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 700x600+1129+656
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2505 1890
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Android Tools"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::label $top.tLa42 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Please select target devices:} 
    vTcl:DefineAlias "$top.tLa42" "TL_select" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu43 \
        -command refresh_devices -takefocus {} -text Refresh 
    vTcl:DefineAlias "$top.tBu43" "TB_refreshdev" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo44 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo44" "TC_devices" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa45 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Device info:} 
    vTcl:DefineAlias "$top.tLa45" "TL_devicesinfo" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr47 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr47" "List_local" vTcl:WidgetProc "Toplevel1" 1

    $top.scr47.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $top.scr48 \
        -background {#d9d9d9} -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr48" "List_device" vTcl:WidgetProc "Toplevel1" 1

    $top.scr48.01 configure -background white \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu49 \
        -command push_file -takefocus {} -text -> 
    vTcl:DefineAlias "$top.tBu49" "TB_push" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.cpd51 \
        -command pull_file -takefocus {} -text <- 
    vTcl:DefineAlias "$top.cpd51" "TB_pull" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.tBu52 \
        -command refresh_dir -takefocus {} -text @ 
    vTcl:DefineAlias "$top.tBu52" "TB_refreshdir" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $top.cpd54 \
        -command install_apk -takefocus {} -text X 
    vTcl:DefineAlias "$top.cpd54" "TB_install" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa36 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Local Path:} 
    vTcl:DefineAlias "$top.tLa36" "TL_localpath" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $top.tLa37 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Device Path:} 
    vTcl:DefineAlias "$top.tLa37" "TL_devicepath" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $top.tPr36
    vTcl:DefineAlias "$top.tPr36" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa42 \
        -in $top -x 10 -y 10 -anchor nw -bordermode ignore 
    place $top.tBu43 \
        -in $top -x 220 -y 20 -anchor nw -bordermode ignore 
    place $top.tCo44 \
        -in $top -x 10 -y 30 -width 207 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.tLa45 \
        -in $top -x 310 -y 0 -width 193 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.scr47 \
        -in $top -x 10 -y 70 -width 316 -height 518 -anchor nw \
        -bordermode ignore 
    place $top.scr48 \
        -in $top -x 380 -y 70 -width 316 -height 518 -anchor nw \
        -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 330 -y 80 -width 44 -height 38 -anchor nw \
        -bordermode ignore 
    place $top.cpd51 \
        -in $top -x 330 -y 130 -width 44 -height 38 -anchor nw \
        -bordermode inside 
    place $top.tBu52 \
        -in $top -x 330 -y 180 -width 44 -height 38 -anchor nw \
        -bordermode ignore 
    place $top.cpd54 \
        -in $top -x 330 -y 230 -width 44 -height 38 -anchor nw \
        -bordermode inside 
    place $top.tLa36 \
        -in $top -x 10 -y 50 -anchor nw -bordermode ignore 
    place $top.tLa37 \
        -in $top -x 350 -y 50 -anchor nw -bordermode ignore 
    place $top.tPr36 \
        -in $top -x 310 -y 20 -width 380 -height 19 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

